// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.ning.message;

public final class ServiceMessage {
  private ServiceMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SrvMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServiceMessage.proto.SrvMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 timestamp = 1;</code>
     */
    long getTimestamp();

    /**
     * <code>optional string mg = 2;</code>
     */
    java.lang.String getMg();
    /**
     * <code>optional string mg = 2;</code>
     */
    com.google.protobuf.ByteString
        getMgBytes();

    /**
     * <code>optional string to = 3;</code>
     */
    java.lang.String getTo();
    /**
     * <code>optional string to = 3;</code>
     */
    com.google.protobuf.ByteString
        getToBytes();

    /**
     * <code>optional string from = 4;</code>
     */
    java.lang.String getFrom();
    /**
     * <code>optional string from = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromBytes();

    /**
     * <code>optional bool group = 5;</code>
     */
    boolean getGroup();

    /**
     * <code>optional uint32 p = 6;</code>
     */
    int getP();

    /**
     * <code>optional .ClientMessage.proto.Message client = 7;</code>
     */
    boolean hasClient();
    /**
     * <code>optional .ClientMessage.proto.Message client = 7;</code>
     */
    com.ning.message.ClientMessage.Message getClient();
    /**
     * <code>optional .ClientMessage.proto.Message client = 7;</code>
     */
    com.ning.message.ClientMessage.MessageOrBuilder getClientOrBuilder();
  }
  /**
   * Protobuf type {@code ServiceMessage.proto.SrvMessage}
   */
  public  static final class SrvMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServiceMessage.proto.SrvMessage)
      SrvMessageOrBuilder {
    // Use SrvMessage.newBuilder() to construct.
    private SrvMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SrvMessage() {
      timestamp_ = 0L;
      mg_ = "";
      to_ = "";
      from_ = "";
      group_ = false;
      p_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SrvMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              mg_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              to_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              from_ = s;
              break;
            }
            case 40: {

              group_ = input.readBool();
              break;
            }
            case 48: {

              p_ = input.readUInt32();
              break;
            }
            case 58: {
              com.ning.message.ClientMessage.Message.Builder subBuilder = null;
              if (client_ != null) {
                subBuilder = client_.toBuilder();
              }
              client_ = input.readMessage(com.ning.message.ClientMessage.Message.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(client_);
                client_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ning.message.ServiceMessage.internal_static_ServiceMessage_proto_SrvMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ning.message.ServiceMessage.internal_static_ServiceMessage_proto_SrvMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ning.message.ServiceMessage.SrvMessage.class, com.ning.message.ServiceMessage.SrvMessage.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>optional uint64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int MG_FIELD_NUMBER = 2;
    private volatile java.lang.Object mg_;
    /**
     * <code>optional string mg = 2;</code>
     */
    public java.lang.String getMg() {
      java.lang.Object ref = mg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mg_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMgBytes() {
      java.lang.Object ref = mg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TO_FIELD_NUMBER = 3;
    private volatile java.lang.Object to_;
    /**
     * <code>optional string to = 3;</code>
     */
    public java.lang.String getTo() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        to_ = s;
        return s;
      }
    }
    /**
     * <code>optional string to = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToBytes() {
      java.lang.Object ref = to_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        to_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROM_FIELD_NUMBER = 4;
    private volatile java.lang.Object from_;
    /**
     * <code>optional string from = 4;</code>
     */
    public java.lang.String getFrom() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        from_ = s;
        return s;
      }
    }
    /**
     * <code>optional string from = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromBytes() {
      java.lang.Object ref = from_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        from_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GROUP_FIELD_NUMBER = 5;
    private boolean group_;
    /**
     * <code>optional bool group = 5;</code>
     */
    public boolean getGroup() {
      return group_;
    }

    public static final int P_FIELD_NUMBER = 6;
    private int p_;
    /**
     * <code>optional uint32 p = 6;</code>
     */
    public int getP() {
      return p_;
    }

    public static final int CLIENT_FIELD_NUMBER = 7;
    private com.ning.message.ClientMessage.Message client_;
    /**
     * <code>optional .ClientMessage.proto.Message client = 7;</code>
     */
    public boolean hasClient() {
      return client_ != null;
    }
    /**
     * <code>optional .ClientMessage.proto.Message client = 7;</code>
     */
    public com.ning.message.ClientMessage.Message getClient() {
      return client_ == null ? com.ning.message.ClientMessage.Message.getDefaultInstance() : client_;
    }
    /**
     * <code>optional .ClientMessage.proto.Message client = 7;</code>
     */
    public com.ning.message.ClientMessage.MessageOrBuilder getClientOrBuilder() {
      return getClient();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (timestamp_ != 0L) {
        output.writeUInt64(1, timestamp_);
      }
      if (!getMgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mg_);
      }
      if (!getToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, to_);
      }
      if (!getFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, from_);
      }
      if (group_ != false) {
        output.writeBool(5, group_);
      }
      if (p_ != 0) {
        output.writeUInt32(6, p_);
      }
      if (client_ != null) {
        output.writeMessage(7, getClient());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, timestamp_);
      }
      if (!getMgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mg_);
      }
      if (!getToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, to_);
      }
      if (!getFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, from_);
      }
      if (group_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, group_);
      }
      if (p_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, p_);
      }
      if (client_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getClient());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ning.message.ServiceMessage.SrvMessage)) {
        return super.equals(obj);
      }
      com.ning.message.ServiceMessage.SrvMessage other = (com.ning.message.ServiceMessage.SrvMessage) obj;

      boolean result = true;
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && getMg()
          .equals(other.getMg());
      result = result && getTo()
          .equals(other.getTo());
      result = result && getFrom()
          .equals(other.getFrom());
      result = result && (getGroup()
          == other.getGroup());
      result = result && (getP()
          == other.getP());
      result = result && (hasClient() == other.hasClient());
      if (hasClient()) {
        result = result && getClient()
            .equals(other.getClient());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + MG_FIELD_NUMBER;
      hash = (53 * hash) + getMg().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGroup());
      hash = (37 * hash) + P_FIELD_NUMBER;
      hash = (53 * hash) + getP();
      if (hasClient()) {
        hash = (37 * hash) + CLIENT_FIELD_NUMBER;
        hash = (53 * hash) + getClient().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ning.message.ServiceMessage.SrvMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ning.message.ServiceMessage.SrvMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServiceMessage.proto.SrvMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServiceMessage.proto.SrvMessage)
        com.ning.message.ServiceMessage.SrvMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ning.message.ServiceMessage.internal_static_ServiceMessage_proto_SrvMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ning.message.ServiceMessage.internal_static_ServiceMessage_proto_SrvMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ning.message.ServiceMessage.SrvMessage.class, com.ning.message.ServiceMessage.SrvMessage.Builder.class);
      }

      // Construct using com.ning.message.ServiceMessage.SrvMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        timestamp_ = 0L;

        mg_ = "";

        to_ = "";

        from_ = "";

        group_ = false;

        p_ = 0;

        if (clientBuilder_ == null) {
          client_ = null;
        } else {
          client_ = null;
          clientBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ning.message.ServiceMessage.internal_static_ServiceMessage_proto_SrvMessage_descriptor;
      }

      public com.ning.message.ServiceMessage.SrvMessage getDefaultInstanceForType() {
        return com.ning.message.ServiceMessage.SrvMessage.getDefaultInstance();
      }

      public com.ning.message.ServiceMessage.SrvMessage build() {
        com.ning.message.ServiceMessage.SrvMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ning.message.ServiceMessage.SrvMessage buildPartial() {
        com.ning.message.ServiceMessage.SrvMessage result = new com.ning.message.ServiceMessage.SrvMessage(this);
        result.timestamp_ = timestamp_;
        result.mg_ = mg_;
        result.to_ = to_;
        result.from_ = from_;
        result.group_ = group_;
        result.p_ = p_;
        if (clientBuilder_ == null) {
          result.client_ = client_;
        } else {
          result.client_ = clientBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ning.message.ServiceMessage.SrvMessage) {
          return mergeFrom((com.ning.message.ServiceMessage.SrvMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ning.message.ServiceMessage.SrvMessage other) {
        if (other == com.ning.message.ServiceMessage.SrvMessage.getDefaultInstance()) return this;
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getMg().isEmpty()) {
          mg_ = other.mg_;
          onChanged();
        }
        if (!other.getTo().isEmpty()) {
          to_ = other.to_;
          onChanged();
        }
        if (!other.getFrom().isEmpty()) {
          from_ = other.from_;
          onChanged();
        }
        if (other.getGroup() != false) {
          setGroup(other.getGroup());
        }
        if (other.getP() != 0) {
          setP(other.getP());
        }
        if (other.hasClient()) {
          mergeClient(other.getClient());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ning.message.ServiceMessage.SrvMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ning.message.ServiceMessage.SrvMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional uint64 timestamp = 1;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional uint64 timestamp = 1;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object mg_ = "";
      /**
       * <code>optional string mg = 2;</code>
       */
      public java.lang.String getMg() {
        java.lang.Object ref = mg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMgBytes() {
        java.lang.Object ref = mg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mg = 2;</code>
       */
      public Builder setMg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mg = 2;</code>
       */
      public Builder clearMg() {
        
        mg_ = getDefaultInstance().getMg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mg = 2;</code>
       */
      public Builder setMgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mg_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object to_ = "";
      /**
       * <code>optional string to = 3;</code>
       */
      public java.lang.String getTo() {
        java.lang.Object ref = to_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          to_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public com.google.protobuf.ByteString
          getToBytes() {
        java.lang.Object ref = to_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          to_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public Builder setTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string to = 3;</code>
       */
      public Builder setToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        to_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object from_ = "";
      /**
       * <code>optional string from = 4;</code>
       */
      public java.lang.String getFrom() {
        java.lang.Object ref = from_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          from_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromBytes() {
        java.lang.Object ref = from_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          from_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public Builder setFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }
      /**
       * <code>optional string from = 4;</code>
       */
      public Builder setFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        from_ = value;
        onChanged();
        return this;
      }

      private boolean group_ ;
      /**
       * <code>optional bool group = 5;</code>
       */
      public boolean getGroup() {
        return group_;
      }
      /**
       * <code>optional bool group = 5;</code>
       */
      public Builder setGroup(boolean value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool group = 5;</code>
       */
      public Builder clearGroup() {
        
        group_ = false;
        onChanged();
        return this;
      }

      private int p_ ;
      /**
       * <code>optional uint32 p = 6;</code>
       */
      public int getP() {
        return p_;
      }
      /**
       * <code>optional uint32 p = 6;</code>
       */
      public Builder setP(int value) {
        
        p_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 p = 6;</code>
       */
      public Builder clearP() {
        
        p_ = 0;
        onChanged();
        return this;
      }

      private com.ning.message.ClientMessage.Message client_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ning.message.ClientMessage.Message, com.ning.message.ClientMessage.Message.Builder, com.ning.message.ClientMessage.MessageOrBuilder> clientBuilder_;
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public boolean hasClient() {
        return clientBuilder_ != null || client_ != null;
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public com.ning.message.ClientMessage.Message getClient() {
        if (clientBuilder_ == null) {
          return client_ == null ? com.ning.message.ClientMessage.Message.getDefaultInstance() : client_;
        } else {
          return clientBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public Builder setClient(com.ning.message.ClientMessage.Message value) {
        if (clientBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          client_ = value;
          onChanged();
        } else {
          clientBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public Builder setClient(
          com.ning.message.ClientMessage.Message.Builder builderForValue) {
        if (clientBuilder_ == null) {
          client_ = builderForValue.build();
          onChanged();
        } else {
          clientBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public Builder mergeClient(com.ning.message.ClientMessage.Message value) {
        if (clientBuilder_ == null) {
          if (client_ != null) {
            client_ =
              com.ning.message.ClientMessage.Message.newBuilder(client_).mergeFrom(value).buildPartial();
          } else {
            client_ = value;
          }
          onChanged();
        } else {
          clientBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public Builder clearClient() {
        if (clientBuilder_ == null) {
          client_ = null;
          onChanged();
        } else {
          client_ = null;
          clientBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public com.ning.message.ClientMessage.Message.Builder getClientBuilder() {
        
        onChanged();
        return getClientFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      public com.ning.message.ClientMessage.MessageOrBuilder getClientOrBuilder() {
        if (clientBuilder_ != null) {
          return clientBuilder_.getMessageOrBuilder();
        } else {
          return client_ == null ?
              com.ning.message.ClientMessage.Message.getDefaultInstance() : client_;
        }
      }
      /**
       * <code>optional .ClientMessage.proto.Message client = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ning.message.ClientMessage.Message, com.ning.message.ClientMessage.Message.Builder, com.ning.message.ClientMessage.MessageOrBuilder> 
          getClientFieldBuilder() {
        if (clientBuilder_ == null) {
          clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ning.message.ClientMessage.Message, com.ning.message.ClientMessage.Message.Builder, com.ning.message.ClientMessage.MessageOrBuilder>(
                  getClient(),
                  getParentForChildren(),
                  isClean());
          client_ = null;
        }
        return clientBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ServiceMessage.proto.SrvMessage)
    }

    // @@protoc_insertion_point(class_scope:ServiceMessage.proto.SrvMessage)
    private static final com.ning.message.ServiceMessage.SrvMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ning.message.ServiceMessage.SrvMessage();
    }

    public static com.ning.message.ServiceMessage.SrvMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SrvMessage>
        PARSER = new com.google.protobuf.AbstractParser<SrvMessage>() {
      public SrvMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SrvMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SrvMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SrvMessage> getParserForType() {
      return PARSER;
    }

    public com.ning.message.ServiceMessage.SrvMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceMessage_proto_SrvMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceMessage_proto_SrvMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\024ServiceMessage.proto\032\023C" +
      "lientMessage.proto\"\215\001\n\nSrvMessage\022\021\n\ttim" +
      "estamp\030\001 \001(\004\022\n\n\002mg\030\002 \001(\t\022\n\n\002to\030\003 \001(\t\022\014\n\004" +
      "from\030\004 \001(\t\022\r\n\005group\030\005 \001(\010\022\t\n\001p\030\006 \001(\r\022,\n\006" +
      "client\030\007 \001(\0132\034.ClientMessage.proto.Messa" +
      "geB\"\n\020com.ning.messageB\016ServiceMessageb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ning.message.ClientMessage.getDescriptor(),
        }, assigner);
    internal_static_ServiceMessage_proto_SrvMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServiceMessage_proto_SrvMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceMessage_proto_SrvMessage_descriptor,
        new java.lang.String[] { "Timestamp", "Mg", "To", "From", "Group", "P", "Client", });
    com.ning.message.ClientMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
